// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillMap.Data;

#nullable disable

namespace SkillMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406144956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillMap.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming",
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming",
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming",
                            IsActive = true,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming",
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Programming",
                            IsActive = true,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Database",
                            IsActive = true,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Database",
                            IsActive = true,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Database",
                            IsActive = true,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Frontend",
                            IsActive = true,
                            Name = "React"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Frontend",
                            IsActive = true,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Frontend",
                            IsActive = true,
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Backend",
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 13,
                            Category = "DevOps",
                            IsActive = true,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 14,
                            Category = "DevOps",
                            IsActive = true,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Tools",
                            IsActive = true,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Soft Skills",
                            IsActive = true,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Soft Skills",
                            IsActive = true,
                            Name = "Team Leadership"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Soft Skills",
                            IsActive = true,
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Languages",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Languages",
                            IsActive = true,
                            Name = "German"
                        });
                });

            modelBuilder.Entity("SkillMap.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillMap.Models.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("SkillMap.Models.UserSkill", b =>
                {
                    b.HasOne("SkillMap.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMap.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
